### ISSUE TITLE
Failed to start: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by spidgrou** [iuriaranda/signalk-mqtt-bridge#7]
Hi,
just installed on my Pi3B+ with venus OS 3.0 Large.
MQTT is running regularly.

After the reboot I see in the SignalK dashboard the error on the subject.
I'm not able to remove it because it does not appear in the AppStore/Installed, it appear only in the AppStore/Available.

Any help is more than appreciated.

![image](https://github.com/iuriaranda/signalk-mqtt-bridge/assets/42083306/b50a4432-cbcf-49a3-a8cd-71613daf845b)

**Comment by iuriaranda** [comment]
hmm strange. It looks like it's failing in this line https://github.com/iuriaranda/signalk-mqtt-bridge/blob/main/index.js#L14 because `app.selfId` is `undefined`.

I say strange because, if no MMSI is set, SignalK normally generates a random ID automatically on first startup. Can you double check your setup settings to see if an ID is present? Should be in Server -> Settings -> Vessel Base data -> UUID (or MMSI)

**Comment by spidgrou** [comment]
Hey,
Got it!
Yes the problem is solved if I put my mmsi in that position, it was empty.

I check also on another signalk with openplotter and I can replicate the problem even there. 

It seems that if the mmsi is empty the plugin doesn't create a uid. 

Thank you!

**Comment by iuriaranda** [comment]
I've added some error handling so it fails gracefully, setting a meaningful error state message in the plugin status in case no UUID or MMSI are set. Since either one of those are necessary to use the plugin, there's not much more we can do.

Thanks for the contribution. I'll go ahead and close the issue now.
